---
# =============================================================================
# Handlers pour le r√¥le ssh-chroot-jail
# =============================================================================

# -----------------------------------------------------------------------------
# Systemd
# -----------------------------------------------------------------------------
- name: reload systemd daemon
  systemd:
    daemon_reload: true

# -----------------------------------------------------------------------------
# Service SSHD jail
# -----------------------------------------------------------------------------
- name: restart sshd jail daemon
  service:
    name: "{{ sshd_jail_daemon }}"
    state: restarted
